name: ci
on:
  push:
    branches:
      - main
permissions:
  contents: write
job:
  deploy:
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@v3
      uses: action/setup-python@v4
      with:
        python-version: 3.x
      uses: action/cache@v2
      with: 
        key: ${{ github.ref }}
        path: .cache
      run: pip install mkdocs-material
      run: mkdocs gh-deploy --force
